#!/bin/sh
if ! whoami > /dev/null 2>&1; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi
rm -rf "/var/build/ws-$(id -u)"
mkdir  "/var/build/ws-$(id -u)"
chmod 700 "/var/build/ws-$(id -u)"
ln -sf "/var/build/ws-$(id -u)" "/var/build/workspace"
exec "$@"
